//
//  Style Guide v9.0
//  
//  Generated by StyleSync
//  https://github.com/dylanslewis/StyleSync
//

import UIKit

extension UIColor {

	public static let sampleBlack = UIColor(red: 0.0, green: 0.0, blue: 0.0, alpha: 1.0)

	public static let sampleGreen = UIColor(red: 0.159652083392304, green: 0.601748511904762, blue: 0.0407433888268849, alpha: 1.0)

	public static let sampleFire = UIColor(red: 0.872395833333333, green: 0.287587669675442, blue: 0.0456610271826336, alpha: 1.0)

	public static let sampleYellow = UIColor(red: 0.824139030612245, green: 0.765277906753585, blue: 0.0262095982746792, alpha: 1.0)

	public static let sampleBlue = UIColor(red: 0.288655698299408, green: 0.564551889896393, blue: 0.886238694190979, alpha: 1.0)

	public static let sampleRed = UIColor(red: 0.885974702380952, green: 0.0899118897776124, blue: 0.187545935695279, alpha: 1.0)

	public static let allGeneratedStylesAndCodeNameAndName: [(UIColor, String, String)] = [
		(.sampleBlack, "sampleBlack", "Sample Black"),
		(.sampleGreen, "sampleGreen", "Sample Green"),
		(.sampleFire, "sampleFire", "Sample Fire"),
		(.sampleYellow, "sampleYellow", "Sample Yellow"),
		(.sampleBlue, "sampleBlue", "Sample Blue"),
		(.sampleRed, "sampleRed", "Sample Red"),
	]
}
