//
//  Style Guide v1.1
//  
//  Generated by stylesync
//  https://github.com/dylanslewis/stylesync
//

import UIKit

extension UIColor {

	/// #C91813
	public static let sampleRed = UIColor(red: 201/255, green: 24/255, blue: 19/255, alpha: 1.0)

	/// #DB0A5B
	public static let samplePink = UIColor(red: 219/255, green: 10/255, blue: 91/255, alpha: 1.0)

	/// #7337AF
	public static let samplePurple = UIColor(red: 115/255, green: 55/255, blue: 175/255, alpha: 1.0)

	/// #446CB3
	public static let sampleBlue = UIColor(red: 68/255, green: 108/255, blue: 179/255, alpha: 1.0)

	/// #26A65B
	public static let sampleGreen = UIColor(red: 38/255, green: 166/255, blue: 91/255, alpha: 1.0)

	/// #F89406
	public static let sampleOrange = UIColor(red: 248/255, green: 148/255, blue: 6/255, alpha: 1.0)

	/// #95A5A6
	public static let sampleGrey = UIColor(red: 149/255, green: 165/255, blue: 166/255, alpha: 1.0)

	/// #000000
	public static let sampleBlack = UIColor(red: 0/255, green: 0/255, blue: 0/255, alpha: 1.0)

	public static let allGeneratedStylesAndCodeNameAndName: [(UIColor, String, String)] = [
		(.sampleRed, "sampleRed", "Sample Red"),
		(.samplePink, "samplePink", "Sample Pink"),
		(.samplePurple, "samplePurple", "Sample Purple"),
		(.sampleBlue, "sampleBlue", "Sample Blue"),
		(.sampleGreen, "sampleGreen", "Sample Green"),
		(.sampleOrange, "sampleOrange", "Sample Orange"),
		(.sampleGrey, "sampleGrey", "Sample Grey"),
		(.sampleBlack, "sampleBlack", "Sample Black"),
	]
}
