//
//  Style Guide v1.0
//  
//  Generated by stylesync
//  https://github.com/dylanslewis/stylesync
//

import UIKit

extension UIColor {

	/// Teal color for backgrounds
	public static let lonaTeal = UIColor(red: 0/255, green: 128/255, blue: 128/255, alpha: 1.0)

	/// Blue accent color
	public static let lonaBlue = UIColor(red: 0/255, green: 0/255, blue: 128/255, alpha: 1.0)

	public static let allGeneratedStylesAndCodeNameAndName: [(UIColor, String, String)] = [
		(.lonaTeal, "lonaTeal", "Lona Teal"),
		(.lonaBlue, "lonaBlue", "Lona Blue"),
	]
}
