//
//  Style Guide v1.0
//  
//  Generated by stylesync
//  https://github.com/dylanslewis/stylesync
//

import UIKit

extension TextStyle {

	static let sampleHeading = TextStyle(
		fontName: "DINAlternate-Bold",
		pointSize: 32,
		color: .sampleRed,
		kerning: 0.8,
		lineHeight: 0
	)

	static let sampleTitle = TextStyle(
		fontName: "DINAlternate-Bold",
		pointSize: 20,
		color: .sampleBlack,
		kerning: 0.8,
		lineHeight: 0
	)

	static let sampleBody = TextStyle(
		fontName: "SFProText-Regular",
		pointSize: 14,
		color: .sampleBlack,
		kerning: 0.0,
		lineHeight: 20
	)

	static let sampleQuote = TextStyle(
		fontName: "SFProText-Italic",
		pointSize: 14,
		color: .sampleBlack,
		kerning: 0.0,
		lineHeight: 20
	)

	static let sampleCaption = TextStyle(
		fontName: "SFProText-Medium",
		pointSize: 10,
		color: .sampleGrey,
		kerning: 0.0,
		lineHeight: 12
	)

	public static let allGeneratedStylesAndCodeNameAndName: [(TextStyle, String, String)] = [
			(.sampleHeading, "sampleHeading", "Sample Heading"),
			(.sampleTitle, "sampleTitle", "Sample Title"),
			(.sampleBody, "sampleBody", "Sample Body"),
			(.sampleQuote, "sampleQuote", "Sample Quote"),
			(.sampleCaption, "sampleCaption", "Sample Caption"),
	]
}
