//
//  Style Guide v1.0
//  
//  Generated by StyleSync
//  https://github.com/dylanslewis/StyleSync
//

import UIKit

public struct TextStyle {
	let font: UIFont
	let color: UIColor
	let kerning: CGFloat
	let lineHeight: CGFloat

	init(
		fontName: String,
		pointSize: CGFloat,
		color: UIColor,
		kerning: CGFloat,
		lineHeight: CGFloat
	) {
		let fontDescriptor = UIFontDescriptor(name: fontName, size: pointSize)
		self.font = UIFont(descriptor: fontDescriptor, size: pointSize)
		self.color = color
		self.kerning = kerning
		self.lineHeight = lineHeight
	}
}

extension TextStyle {

	static let sampleHeading = TextStyle(
		fontName: "FuturaPTHeavy-Reg",
		pointSize: 60,
		color: sampleBlack,
		kerning: 1.5,
		lineHeight: 72
	)

	static let sampleBody = TextStyle(
		fontName: ".SFUIDisplay-Medium",
		pointSize: 12,
		color: sampleBlack,
		kerning: 0.6,
		lineHeight: 30
	)

	static let sampleCaption = TextStyle(
		fontName: ".SFUIText-Light",
		pointSize: 8,
		color: sampleGreen,
		kerning: 0.4,
		lineHeight: 30
	)
}

extension NSAttributedString {
	private static func attributes(for textStyle: TextStyle) -> [NSAttributedStringKey: Any] {
		let paragraphStyle = NSMutableParagraphStyle()
		paragraphStyle.maximumLineHeight = textStyle.lineHeight
		return [
			.font: textStyle.font,
			.foregroundColor: textStyle.color,
			.kern: textStyle.kerning,
			.paragraphStyle: paragraphStyle
		]
	}

	public convenience init(string: String, textStyle: TextStyle) {
		let attributes = NSAttributedString.attributes(for: textStyle)
		self.init(string: string, attributes: attributes)
	}
}
