//
//  Style Guide v1.1
//  
//  Generated by stylesync
//  https://github.com/dylanslewis/stylesync
//

import UIKit

extension TextStyle {

	static let sampleHeading = TextStyle(
		fontName: "DINAlternate-Bold",
		pointSize: 32,
		color: .sampleBlue,
		kerning: 0.8,
		lineHeight: 37
	)

	static let sampleTitle = TextStyle(
		fontName: "DINAlternate-Bold",
		pointSize: 18,
		color: .sampleBlack,
		kerning: 0.72,
		lineHeight: 24
	)

	static let sampleBody = TextStyle(
		fontName: "DINAlternate-Bold",
		pointSize: 14,
		color: .sampleBlack,
		kerning: 0.0,
		lineHeight: 20
	)

	static let sampleQuote = TextStyle(
		fontName: ".SFUIText-Italic",
		pointSize: 14,
		color: .sampleBlack,
		kerning: 0.0,
		lineHeight: 20
	)

	static let sampleCaption = TextStyle(
		fontName: "DINAlternate-Bold",
		pointSize: 10,
		color: .sampleGrey,
		kerning: 0.0,
		lineHeight: 12
	)

	static let newStyle = TextStyle(
		fontName: "DINAlternate-Bold",
		pointSize: 22,
		color: .sampleBlack,
		kerning: 0.72,
		lineHeight: 21
	)

	public static let allGeneratedStylesAndCodeNameAndName: [(TextStyle, String, String)] = [
			(.sampleHeading, "sampleHeading", "Sample Heading"),
			(.sampleTitle, "sampleTitle", "Sample Title"),
			(.sampleBody, "sampleBody", "Sample Body"),
			(.sampleQuote, "sampleQuote", "Sample Quote"),
			(.sampleCaption, "sampleCaption", "Sample Caption"),
			(.newStyle, "newStyle", "New Style"),
	]
}
